### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by pinobatch** [nununoisy/nsf-presenter-rs#1]
Please [choose a free software license](https://choosealicense.com/) for this project. If a program has [no license](https://choosealicense.com/no-permission/), nobody is allowed to use it in a meaningful way. As RusticNES developer zeta0134 put it in the `#chiptuning` channel of the NESdev Discord server:

> I can see it's using ffmpeg-next, but I'm not allowed to learn from the source code without a license

**Comment by nununoisy** [comment]
Done. I had intended to get a license in the first time but missed it between the final changes before release. Hopefully this code can be of some use now!
