### ISSUE TITLE
RusticNES has migrated to Rustico.

### ISSUE THREAD

**Issue by Gumball2415** [nununoisy/nsf-presenter-rs#13]
RusticNES has been renamed and migrated to [Rustico](https://github.com/zeta0134/rustico). You may need to update accordingly.

**Comment by nununoisy** [comment]
I am aware, but thanks for letting me know. Migrating to upstream Rustico is part of the roadmap for v0.7.0, but I'll need to do some refactoring on my end to get everything integrated properly. I've already coordinated with Zeta to ensure I get the branding right in the about dialog and README.
