### ISSUE TITLE
[Feature Request] Automatically append extension to output filename

### ISSUE THREAD

**Issue by N-SPC700** [nununoisy/nsf-presenter-rs#4]
In almost every other Windows application, typing the filename without the extension automatically appends one, except if the filename includes the exact extension that is going to be appended. 
![image](https://github.com/nununoisy/nsf-presenter-rs/assets/38848267/92155b32-a8af-44ed-a1f9-ee2583f85d52)

At the same time, changing the "Save as type" to "All" already exhibits this behavior. Not that it's useful though, as the program throws an error if _anything_ but an .mp4 extension is used.
![image](https://github.com/nununoisy/nsf-presenter-rs/assets/38848267/61dfbcc7-e0c1-49e3-ac76-f663828ae130)

--

The intended solution here is to automatically append the wanted extension (in this case, .mp4) to the output file, and avoid having to deal with the "This output file is not an mp4" error constantly when simply typing just the filename and then pressing Enter/Save.

**Comment by nununoisy** [comment]
This is an annoying oversight in the FLTK file dialog as far as I can tell. I'm currently working on porting the GUI to Slint and using RFD for the dialogs which doesn't have this issue.

As far as requiring `.mp4` files, it's just a result of FFmpeg crashing mysteriously if I try anything else. I'd like to support other formats at some point but that's not a necessity at the moment.

**Comment by N-SPC700** [comment]
Good to know the main issue will be fixed soon. I am also very interested in seeing what other formats can be supported; I personally would really like .mkv to be supported at some point.

**Comment by nununoisy** [comment]
This is fixed in 0.2.0. I'll make a separate issue to track the option to use other output formats.
