### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by MusicBoiJBoy** [nununoisy/nsf-presenter-rs#5]
![5DBFE0D5-0A2C-4919-B4AA-DFA1BE8DF624](https://github.com/nununoisy/nsf-presenter-rs/assets/103322811/8842ea06-f85c-426c-a3a0-844e171603df)
![D1B7F643-8FC8-4C3C-8358-A2F0D64B09E3](https://github.com/nununoisy/nsf-presenter-rs/assets/103322811/6b574c95-73b0-4e11-9ffc-28587b745d14)

wtf

**Comment by nununoisy** [comment]
The loop detection works by reading some FamiTracker NSF driver variables out of the emulator's RAM. Using certain mappers can cause those values to move around which causes the loop detection to read garbage data, causing issues like what you're seeing. In this case, it's VRC7, which I haven't gotten around to properly supporting as RusticNES does not currently support VRC7. I'll fix this issue for the next release, but know that the VRC7 channels will be silent until support is added upstream.

**Comment by nununoisy** [comment]
Fixed in 0.2.0
