### ISSUE TITLE
Manual input for fadeout frames no longer works

### ISSUE THREAD

**Issue by ZeroJanitor** [nununoisy/nsf-presenter-rs#8]
In 0.1.0 you could type in your fadeout frames manually, but in 0.3.0, you have to use the arrows and change the value one frame at a time.

**Comment by nununoisy** [comment]
This is an issue in Slint that has been fixed in their latest release. Once I finish the new NSFPresenter features that fix will be integrated. For now, you can also hold the up/down arrow keys while the box is focused to change the value much faster.

**Comment by nununoisy** [comment]
Should be fixed in v0.4.0.
